#!/usr/bin/bash
#
# Source code checks (python).
#
# Run in top level
# Rwquires
# - pylint
# - pycodestyle
# - mypy
# - cppcheck
# 

dest=($realpath "./src")
export PYTHONPATH="$dest"
mod="$dest"/'wg_client'

echo "---------------------"
echo "Python pylint:"

PYTHONPATH=. pylint "$mod"/*.py "$mod"/*/*.py
PYTHONPATH=. pycodestyle --max-line-length=110 "$mod"/*.py "$mod"/*/*.py

echo ""
echo "---------------------"
echo "Python mypy:"
mypy --check-untyped-defs --follow-untyped-imports "$mod"

echo ""
echo "---------------------"
echo "C-code checks:"
code_dir="src/resolv-manager"
#opts="--enable=style,warning"
#/usr/bin/cppcheck "$opts" "$code_dir"/*.[ch]

/usr/bin/clang-tidy -p build/release "$code_dir"/*.[ch]


